name = "logout"
main = "src/index.js"
account_id = "41f6f507a22c7eec431dbc5e9670c73d"
compatibility_date = "2023-01-07"

kv_namespaces = [
    { binding = "MY_KV", id = "0fa41388238d45819a302d18ecdb3d5b" }
]

[[r2_buckets]]
binding = 'MY_BUCKET' 
bucket_name = 'bucket1'

routes = [
    { pattern = "reportbase.com/logout", zone_id = "41f6f507a22c7eec431dbc5e9670c73d" }
]





